FinanceManager/Models/Product.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace FinanceManager.Models
{
    public class Product
    {
        public int ID { get; set; }

        [StringLength(30, MinimumLength = 3)]
        [Required]
        public string Name { get; set; }

        [Required]
        public float Quantity { get; set; }

        [Display(Name = "Product type")]
        [Required]
        public ProductTypeEnum ProductType { get; set; }

        [Required]
        public float Cost { get; set; }

        [Display(Name = "Cost per unit")]
        public float CostPerUnit { get; set; }

        [Display(Name = "For Who")]
        [StringLength(30, MinimumLength = 3)]
        public string ForWho { get; set; }

        [Display(Name = "Minimal necessary")]
        [DefaultValue(false)]
        public bool IsMinimalNecesarry { get; set; }

        public string FileOriginalName { get; set; }

        public string FileName { get; set; }

        [NotMapped]
        public int PurchaseIdReceiver { get; set; }

        public virtual Purchase Purchase { get; set; }
    }
}

FinanceManager/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FinanceManager.Models;
using FinanceManager.Services;

namespace FinanceManager.Controllers
{
    public class ProductsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Products
        //[ActionName("products")]
        public ActionResult Index()
        {
            return View(db.Products.ToList());
        }

        // GET: Products/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // GET: Products/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Products/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Name,Quantity,ProductType,Cost,CostPerUnit,ForWho,IsMinimalNecesarry,PurchaseIdReceiver")] Product product)
        {
            if (ModelState.IsValid)
            {
                foreach (string upload in Request.Files)
                {
                    if (Request.Files[upload].ContentLength == 0) continue;
                    string pathToSave = Server.MapPath(GlobalConstants.PATH_UPLOADED_IMAGES);
                    if (!Directory.Exists(pathToSave))
                    {
                        Directory.CreateDirectory(pathToSave);
                    }
                    string filename = Path.GetFileName(Request.Files[upload].FileName);
                    string[] extension = filename.Split('.');

                    string serverFileName = FileUploader.GenerateUniqName() + "." + extension[extension.Length - 1];

                    Request.Files[upload].SaveAs(Path.Combine(pathToSave, serverFileName));
                    product.FileName = serverFileName;
                    product.FileOriginalName = filename;
                }

                var purchase = db.Purchases.Find(product.PurchaseIdReceiver);
                //roduct.Purchase = purchase.CastToSelf();
                product.Purchase = purchase;

                db.Products.Add(product);
                db.SaveChanges();
                return PartialView("ApiProductIndex", product);
                //return RedirectToAction("Index");
            }

            return View("ApiProductIndex", product);
        }

        // GET: Products/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Name,Quantity,ProductType,Cost,CostPerUnit,ForWho,IsMinimalNecesarry")] Product product)
        {
            if (ModelState.IsValid)
            {
                db.Entry(product).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(product);
        }

        // GET: Products/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = db.Products.Find(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Product product = db.Products.Find(id);
            var purchaseId = product.Purchase.ID;
            db.Products.Remove(product);
            db.SaveChanges();

            return RedirectToAction("Details", new { controller = "Purchases", id = purchaseId });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FinanceManager/Views/Products/ApiProductIndex.cshtml
@model FinanceManager.Models.Product

<tr>
    <td>
        @Html.DisplayFor(model => model.Name)
    </td>
    <td>
        @Html.DisplayFor(model => model.Quantity)
    </td>
    <td>
        @Html.DisplayFor(model => model.ProductType)
    </td>
    <td>
        @Html.DisplayFor(model => model.Cost)
    </td>
    <td>
        @Html.DisplayFor(model => model.CostPerUnit)
    </td>
    <td>
        @Html.DisplayFor(model => model.ForWho)
    </td>
    <td>
        @Html.DisplayFor(model => model.IsMinimalNecesarry)
    </td>
    <td>
        @if (@Model.FileName != null)
        {
            <img style="width: 40px; height: 40px; margin: -5px 0px -5px 50px;" src="~/Uploads/@Model.FileName" alt="" />
        }
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = @Model.ID }) |
            @Html.ActionLink("Details", "Details", new { id = @Model.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id = @Model.ID })
        </td>
    </tr>

FinanceManager/Views/Products/Create.cshtml
@model FinanceManager.Models.Product

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@RenderPage("Form.cshtml")

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

FinanceManager/Views/Products/Delete.cshtml
@model FinanceManager.Models.Product

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Product</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quantity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProductType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cost)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cost)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CostPerUnit)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CostPerUnit)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ForWho)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ForWho)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsMinimalNecesarry)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsMinimalNecesarry)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FileName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FileName)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

FinanceManager/Views/Products/Details.cshtml
@model FinanceManager.Models.Product

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Product</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quantity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ProductType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ProductType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cost)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cost)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CostPerUnit)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CostPerUnit)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ForWho)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ForWho)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsMinimalNecesarry)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsMinimalNecesarry)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FileName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FileName)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

FinanceManager/Views/Products/Edit.cshtml
@model FinanceManager.Models.Product

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Product</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProductType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.ProductType, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ProductType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cost, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cost, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cost, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CostPerUnit, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CostPerUnit, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CostPerUnit, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ForWho, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ForWho, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ForWho, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsMinimalNecesarry, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsMinimalNecesarry)
                    @Html.ValidationMessageFor(model => model.IsMinimalNecesarry, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FileName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FileName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FileName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

FinanceManager/Views/Products/Form.cshtml
@model FinanceManager.Models.Product

@using (Html.BeginForm("Create", "Products", FormMethod.Post, new { enctype = "multipart/form-data", id = "product-create" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Product</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ProductType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.ProductType, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ProductType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cost, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cost, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cost, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CostPerUnit, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CostPerUnit, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CostPerUnit, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ForWho, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ForWho, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ForWho, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsMinimalNecesarry, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsMinimalNecesarry)
                    @Html.ValidationMessageFor(model => model.IsMinimalNecesarry, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <label for="product-image-tag">Image</label>
            <div class="col-md-10">
                <input type="file" name="Image" id="image-tag" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" id="product-create-btn" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

FinanceManager/Views/Products/FormHtml.cshtml
<form action="/Products/Create" enctype="multipart/form-data" id="product-create" method="post">
    <input name="__RequestVerificationToken" type="hidden" value="He6eP5lyNogrqqmeyte8BzZ8zztdYc7FmINawvoeQ_S21jCB28YeKW-N1NqLm91qg8QyKd2YK7rOFd_UiDSQ2UPKXtilRBgdY_W8OSl0RuE1">
    <input id="PurchaseIdReceiver" name="PurchaseIdReceiver" type="hidden" value="">
    <div class="form-horizontal">
        <h4>Product</h4>
        <hr>

        <div class="form-group">
            <label class="control-label col-md-2" for="Name">Name</label>
            <div class="col-md-10">
                <input class="form-control text-box single-line" id="Name" name="Name" type="text" value="">

            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="Quantity">Quantity</label>
            <div class="col-md-10">
                <input class="form-control text-box single-line" id="Quantity" name="Quantity" type="text" value="">

            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="ProductType">Product type</label>
            <div class="col-md-10">
                <select class="form-control" id="ProductType" name="ProductType">
                    <option selected="selected" value="0">Service</option>
                    <option value="1">Countable</option>
                </select>

            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="Cost">Cost</label>
            <div class="col-md-10">
                <input class="form-control text-box single-line" id="Cost" name="Cost" type="text" value="">

            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="CostPerUnit">Cost per unit</label>
            <div class="col-md-10">
                <input class="form-control text-box single-line" id="CostPerUnit" name="CostPerUnit" type="text" value="">

            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="ForWho">For Who</label>
            <div class="col-md-10">
                <input class="form-control text-box single-line" id="ForWho" name="ForWho" type="text" value="">

            </div>
        </div>

        <div class="form-group">
            <label class="control-label col-md-2" for="IsMinimalNecesarry">Minimal necessary</label>
            <div class="col-md-10">
                <div class="checkbox">
                    <input class="check-box" id="IsMinimalNecesarry" name="IsMinimalNecesarry" type="checkbox" value="true"><input name="IsMinimalNecesarry" type="hidden" value="false">

                </div>
            </div>
        </div>

        <div class="form-group">
            <label for="product-image-tag">Image</label>
            <div class="col-md-10">
                <input type="file" name="Image" id="image-tag">
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" id="product-create-btn" value="Create" class="btn btn-default">
            </div>
        </div>
    </div>
</form>

FinanceManager/Views/Products/Index.cshtml
@model IEnumerable<FinanceManager.Models.Product>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Quantity)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ProductType)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Cost)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CostPerUnit)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ForWho)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsMinimalNecesarry)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FileName)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Quantity)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ProductType)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Cost)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CostPerUnit)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ForWho)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IsMinimalNecesarry)
        </td>
        <td>
            @if (item.FileName != null)
            {
                <img style="width: 40px; height: 40px; margin: -5px 0px -5px 50px;" src="~/Uploads/@item.FileName" alt="" />
            }
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })
        </td>
    </tr>
}

</table>